#install.packages("ggplot2",repos = "http://cran.us.r-project.org")
#install.packages("gridExtra",repos = "http://cran.us.r-project.org")
options( warn = -1 )
library(ggplot2)
library(gridExtra)
library(grid)
temp = list.files(pattern="release.*")
for (i in 1:length(temp))
{
  assign(paste0("release",i), read.csv(temp[i]))
}

par(mfrow=c(2,2),cex.lab=0.8,cex.main=0.8)

#using ggplot
for(i in 1:30)
{
  release<-get(paste0("release",i))
  input = readline(paste('Press Enter to view "Defect Age" Plot for release',i))
  plot1<-ggplot(data=release,aes(x=numActive,y=Total.num.days))+ geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Total Num of Days')+ggtitle("Total Num of Days Vs. Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot2<-ggplot(data=release,aes(x=numDaysActive,y=Total.num.days))+ geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot3<-ggplot(data=release,aes(x=numReopened,y=Total.num.days))+ geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot4<-ggplot(data=release,aes(x=LOC,y=Total.num.days))+ geom_point(color='darkblue')+xlab('Lines of Code')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs. Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  grid.arrange(plot1,plot2,plot3,plot4,ncol=2,top = textGrob(paste("Plot for 'Defect Age' in release",i),gp=gpar(fontsize=13, col="red")))
  input = readline(paste('Press Enter to view "Dev Hours" Plot for release',i))
  plot5<-ggplot(data=release,aes(x=numActive,y=Num.eff.dev.hours))+ geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot6<-ggplot(data=release,aes(x=numDaysActive,y=Num.eff.dev.hours))+ geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot7<-ggplot(data=release,aes(x=numReopened,y=Num.eff.dev.hours))+ geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot8<-ggplot(data=release,aes(x=LOC,y=Num.eff.dev.hours))+ geom_point(color='darkblue')+xlab('Lines of Code')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  grid.arrange(plot5,plot6,plot7,plot8,ncol=2,top = textGrob(paste("Plot for 'Dev Hours' in release",i),gp=gpar(fontsize=13, col="red")))
  input = readline(paste('Press Enter to view "Testing Hours" Plot for release',i))
  plot9<-ggplot(data=release,aes(x=numActive,y=Num.eff.testing.hours))+ geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot10<-ggplot(data=release,aes(x=numDaysActive,y=Num.eff.testing.hours))+ geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot11<-ggplot(data=release,aes(x=numReopened,y=Num.eff.testing.hours))+ geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  plot8<-ggplot(data=release,aes(x=LOC,y=Num.eff.testing.hours)) + geom_point(color='darkblue')+xlab('Lines of Code')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=10,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
  grid.arrange(plot9,plot10,plot11,plot8,ncol=2,top = textGrob(paste("Plot for 'Test Hours' in release",i),gp=gpar(fontsize=13, col="red")))
}
#Shrinking the 30 releases
output_dataset<-data.frame(Rel_Num=double(),Num_Active=integer(),Num_Days_Active=integer(),Num_Reop=integer(),Tot_LOC=integer(),Tot_Days=double(),Tot_Dev_Hrs=double(),Tot_Test_Hrs=double(),Num_Sev_High=integer(),Num_Sev_Med=integer(),Num_Sev_Low=integer());
for (i in 1:30)
{
  release<-get(paste0("release",i))
  x<-data.frame(i,sum(release$numActive),sum(release$numDaysActive),sum(release$numReopened),sum(release$LOC),sum(release$Total.num.days),sum(release$Num.eff.dev.hours),sum(release$Num.eff.testing.hours),nrow(release[release$Severity=='High',]),nrow(release[release$Severity=='Medium',]),nrow(release[release$Severity=='Low',]),nrow(release[release$Priority=='High',]),nrow(release[release$Priority=='Medium',]),nrow(release[release$Priority=='Low',]))
  #x<-cbind("Rel_Num"=i,x)
  names(x)<-c("Rel_num","NumActive","NumDaysActive","NumReopened","Tot_LOC","Tot_Days","Tot_Dev_Hrs","Tot_Test_Hrs","Num_Sev_High","Num_Sev_Med","Num_Sev_Low","Num_Priot_High","Num_Priot_Med","Num_Priot_Low")
  output_dataset<-rbind(output_dataset,x)
}

output_model_TotDays<-lm(Tot_Days ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_DevHrs<-lm(Tot_Dev_Hrs ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_testHrs<-lm(Tot_Test_Hrs ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_high_model<-lm(Num_Sev_High ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_medium_model<-lm(Num_Sev_Med ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_low_model<-lm(Num_Sev_Low ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_priot_high_model<-lm(Num_Priot_High ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_priot_medium_model<-lm(Num_Priot_Med ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_priot_low_model<-lm(Num_Priot_Low ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)

# Shrinked file graph using ggplot
input = readline('Press Enter to view "Total Number of Days" Trend analysis among all the releases')
a<-ggplot(data=output_dataset,aes(x=NumActive,y=Tot_Days)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
b<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Tot_Days))+ geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
c<-ggplot(data=output_dataset,aes(x=NumReopened,y=Tot_Days))+ geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
d<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Tot_Days)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Total Num of Days')+ggtitle("Total Num of Days  Vs. Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(a,b,c,d, ncol=2,top = textGrob("Trend analysis for 'Total Number of Days' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Total Dev Hours" Trend analysis among all the releases')
d<-ggplot(data=output_dataset,aes(x=NumActive,y=Tot_Dev_Hrs)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
e<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Tot_Dev_Hrs)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
f<-ggplot(data=output_dataset,aes(x=NumReopened,y=Tot_Dev_Hrs)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
g<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Tot_Dev_Hrs)) + geom_point(color='darkblue')+xlab('TotalLines of Code')+ylab('Eff. Dev Hours')+ggtitle("Eff. Dev Hours  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(d,e,f,g, ncol=2,top = textGrob("Trend analysis for 'Total Dev Hours' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Total Testing Hours" Trend analysis among all the releases')
h<-ggplot(data=output_dataset,aes(x=NumActive,y=Tot_Test_Hrs)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
i<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Tot_Test_Hrs)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
j<-ggplot(data=output_dataset,aes(x=NumReopened,y=Tot_Test_Hrs)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
k<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Tot_Test_Hrs)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Eff. Testing Hours')+ggtitle("Eff. Testing Hours  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(h,i,j,k, ncol=2,top = textGrob("Trend analysis for 'Total Testing Hours' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Number of High Severity Defects" Trend analysis among all the releases')
l<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Sev_High)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Number of High Sev defects')+ggtitle("Number of High severity defects  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
m<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Sev_High)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Number of High Sev defects')+ggtitle("Number of High severity defects  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
n<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Sev_High)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Number of High Sev defects')+ggtitle("Number of High severity defects  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
o<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Sev_High)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Number of High Sev defects')+ggtitle("Number of High severity defects  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(l,m,n,o, ncol=2,top = textGrob("Trend analysis for 'Number of High Severity Defects' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Number of Medium Severity Defects" Trend analysis among all the releases')
p<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Sev_Med)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Number of Medium Sev defects')+ggtitle("Number of Medium severity defects  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
q<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Sev_Med)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Number of Medium Sev defects')+ggtitle("Number of Medium severity defects  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
r<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Sev_Med)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Number of Medium Sev defects')+ggtitle("Number of Medium severity defects  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
s<-ggplot(data=output_dataset,aes(x=Tot_LOC,output_dataset,y=Num_Sev_Med)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Number of Medium Sev defects')+ggtitle("Number of Medium severity defects  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(p,q,r,s, ncol=2,top = textGrob("Trend analysis for 'Number of Medium Severity Defects' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Number of Low Severity Defects" Trend analysis for all the releases')
t<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Sev_Low)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Number of Low Sev defects')+ggtitle("Number of Low severity defects  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
u<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Sev_Low)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Number of Low Sev defects')+ggtitle("Number of Low severity defects  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
v<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Sev_Low))+ geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Number of Low Sev defects')+ggtitle("Number of Low severity defects  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
w<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Sev_Low))+ geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Number of Low Sev defects')+ggtitle("Number of Low severity defects  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(t,u,v,w, ncol=2,top = textGrob("Trend analysis for 'Number of Low Severity Defects' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Number of High Priority Defects" Trend analysis among all the releases')
x<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Priot_High)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Number of High Prior defects')+ggtitle("Number of High priority defects  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
y<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Priot_High)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Number of High Prior defects')+ggtitle("Number of High priority defects  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
z<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Priot_High)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Number of High Prior defects')+ggtitle("Number of High priority defects  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
aa<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Priot_High)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Number of High Prior defects')+ggtitle("Number of High priority defects  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(x,y,z,aa, ncol=2,top = textGrob("Trend analysis for 'Number of High Priority Defects' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Number of Medium Priority Defects" Trend analysis among all the releases')
bb<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Priot_Med)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Number of Medium Prior defects')+ggtitle("Number of Medium priority defects  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
cc<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Priot_Med)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Number of Medium Prior defects')+ggtitle("Number of Medium priority defects  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
dd<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Priot_Med)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Number of Medium Prior defects')+ggtitle("Number of Medium priority defects  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
ee<-ggplot(data=output_dataset,aes(x=Tot_LOC,output_dataset,y=Num_Priot_Med)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Number of Medium Prior defects')+ggtitle("Number of Medium priority defects  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(bb,cc,dd,ee, ncol=2,top = textGrob("Trend analysis for 'Number of Medium Priority Defects' among all the 30 releases",gp=gpar(fontsize=13, col="red")))
input = readline('Press Enter to view "Number of Low Priority Defects" Trend analysis for all the releases')
ff<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Priot_Low)) + geom_point(color='darkblue')+xlab('Number of times Active')+ylab('Number of Low Prior defects')+ggtitle("Number of Low priority defects  Vs.  Number of times Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
gg<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Priot_Low)) + geom_point(color='darkblue')+xlab('Number of days Active')+ylab('Number of Low Prior defects')+ggtitle("Number of Low priority defects  Vs.  Number of days Active")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
hh<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Priot_Low)) + geom_point(color='darkblue')+xlab('Number of times Reopened')+ylab('Number of Low Prior defects')+ggtitle("Number of Low priority defects  Vs.  Number of times Reopened")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
ii<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Priot_Low)) + geom_point(color='darkblue')+xlab('Total Lines of Code')+ylab('Number of Low Prior defects')+ggtitle("Number of Low priority defects  Vs.  Total Lines of Code")+theme(axis.text=element_text(size=8),axis.title=element_text(size=7,face="bold"),plot.title = element_text(size = 8, face = "bold", colour="blue", hjust = 0.5))
grid.arrange(ff,gg,hh,ii, ncol=2,top = textGrob("Trend analysis for 'Number of Low Priority Defects' among all the 30 releases",gp=gpar(fontsize=13, col="red")))

input = readline('***********************Total Number of days Prediction for future release based on input Features************************')
summary(output_model_TotDays)
plot(output_model_TotDays)
mtext("Validation of Prediction Model for Total number days of QA defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Eff Dev Hours Prediction for future release based on input Features*************************')
summary(output_model_DevHrs)
plot(output_model_DevHrs)
mtext("Validation of Prediction Model for Total Eff Dev Hours of QA defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Eff Testing Hours Prediction for future release based on input Features***********************')
summary(output_model_testHrs)
plot(output_model_testHrs)
mtext("Validation of Prediction Model for Total Eff Testing Hours of QA defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of High Severity Defects Prediction for future release based on input Features***********************')
summary(output_model_svr_high_model)
plot(output_model_svr_high_model)
mtext("Validation of Prediction Model for Total Number of High Severity Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Medium Severity Defects Prediction for future release based on input Features***********************')
summary(output_model_svr_medium_model)
plot(output_model_svr_medium_model)
mtext("Validation of Prediction Model for Total Number of Medium Severity Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Low Severity Defects Prediction for future release based on input Features***********************')
summary(output_model_svr_low_model)
plot(output_model_svr_low_model)
mtext("Validation of Prediction Model for Total Number of Low Severity Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of High Priority Defects Prediction for future release based on input Features***********************')
summary(output_model_priot_high_model)
plot(output_model_priot_high_model)
mtext("Validation of Prediction Model for Total Number of High Priority Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Medium Priority Defects Prediction for future release based on input Features***********************')
summary(output_model_priot_medium_model)
plot(output_model_priot_medium_model)
mtext("Validation of Prediction Model for Total Number of Medium Priority Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Low Priority Defects Prediction for future release based on input Features***********************')
summary(output_model_priot_low_model)
plot(output_model_priot_low_model)
mtext("Validation of Prediction Model for Total Number of Low Priority Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)

