install.packages("ggplot2",repos = "http://cran.us.r-project.org")
library(ggplot2)
temp = list.files(pattern="release.*")
for (i in 1:length(temp))
{
  assign(paste0("release",i), read.csv(temp[i]))
}

par(mfrow=c(2,2),cex.lab=0.8,cex.main=0.8)

#using ggplot
for(i in 1:30)
{
  release<-get(paste0("release",i))
  input = readline(paste('Press Enter to view "Defect Age" Plot for release',i))
  plot1<-ggplot(data=release,aes(x=numActive,y=Total.num.days),main=paste0("Total Num of Days Vs. Number of times Active\n Release",i),xlab='Number of times Active',ylab='Total Num of Days')+ geom_point(color='darkblue')
  plot2<-ggplot(data=release,aes(x=numDaysActive,y=Total.num.days),main=paste0("Total Num of Days  Vs.  Number of days Active\n Release",i),xlab='Number of days Active',ylab='Total Num of Days')+ geom_point(color='darkblue')
  plot3<-ggplot(data=release,aes(x=numReopened,y=Total.num.days),main=paste0("Total Num of Days  Vs.  Number of times Reopened\n Release",i),xlab='Number of times Reopened',ylab='Total Num of Days')+ geom_point(color='darkblue')
  plot4<-ggplot(data=release,aes(x=LOC,y=Total.num.days),main=paste0("Total Num of Days  Vs. Lines of Code\n Release",i),xlab='Lines of Code',ylab='Total Num of Days')+ geom_point(color='darkblue')
  grid.arrange(plot1,plot2,plot3,plot4,ncol=2,top = textGrob(paste("Plot for 'Defect Age' in release",i),gp=gpar(fontsize=10, font=2)))
  input = readline(paste('Press Enter to view "Dev Hours" Plot for release',i))
  plot5<-ggplot(data=release,aes(x=numActive,y=Num.eff.dev.hours),main=paste0("Eff. Dev Hours  Vs.  Number of times Active\n Release",i),xlab='Number of times Active',ylab='Eff. Dev Hours')+ geom_point(color='darkblue')
  plot6<-ggplot(data=release,aes(x=numDaysActive,y=Num.eff.dev.hours),main=paste0("Eff. Dev Hours  Vs.  Number of days Active\n Release",i),xlab='Number of days Active',ylab='Eff. Dev Hours')+ geom_point(color='darkblue')
  plot7<-ggplot(data=release,aes(x=numReopened,y=Num.eff.dev.hours),main=paste0("Eff. Dev Hours  Vs.  Number of times Reopened\n Release",i),xlab='Number of times Reopened',ylab='Eff. Dev Hours')+ geom_point(color='darkblue')
  plot8<-ggplot(data=release,aes(x=LOC,y=Num.eff.dev.hours),main=paste0("Eff. Dev Hours  Vs.  Lines of Code\n Release",i),xlab='Lines of Code',ylab='Eff. Dev Hours')+ geom_point(color='darkblue')
  grid.arrange(plot5,plot6,plot7,plot8,ncol=2,top = textGrob(paste("Plot for 'Dev Hours' in release",i),gp=gpar(fontsize=10, font=2)))
  input = readline(paste('Press Enter to view "Testing Hours" Plot for release',i))
  plot9<-ggplot(data=release,aes(x=numActive,y=Num.eff.testing.hours),main=paste0("Eff. Testing Hours  Vs.  Number of times Active\n Release",i),xlab='Number of times Active',ylab='Eff. Testing Hours')+ geom_point(color='darkblue')
  plot10<-ggplot(data=release,aes(x=numDaysActive,y=Num.eff.testing.hours),main=paste0("Eff. Testing Hours  Vs.  Number of days Active\n Release",i),xlab='Number of days Active',ylab='Eff. Testing Hours')+ geom_point(color='darkblue')
  plot11<-ggplot(data=release,aes(x=numReopened,y=Num.eff.testing.hours),main=paste0("Eff. Testing Hours  Vs.  Number of times Reopened\n Release",i),xlab='Number of times Reopened',ylab='Eff. Testing Hours')+ geom_point(color='darkblue')
  plot12<-ggplot(data=release,aes(x=LOC,y=Num.eff.testing.hours),main=paste0("Eff. Testing Hours  Vs.  Lines of Code\n Release",i),xlab='Lines of Code',ylab='Eff. Testing Hours') + geom_point(color='darkblue')
  grid.arrange(plot9,plot10,plot11,plot12,ncol=2,top = textGrob(paste("Plot for 'Test Hours' in release",i),gp=gpar(fontsize=10, font=2)))
}
#Shrinking the 30 releases
output_dataset<-data.frame(Rel_Num=double(),Num_Active=integer(),Num_Days_Active=integer(),Num_Reop=integer(),Tot_LOC=integer(),Tot_Days=double(),Tot_Dev_Hrs=double(),Tot_Test_Hrs=double(),Num_Sev_High=integer(),Num_Sev_Med=integer(),Num_Sev_Low=integer());
for (i in 1:30)
{
  release<-get(paste0("release",i))
  x<-data.frame(sum(release$numDaysActive),sum(release$numActive),sum(release$numReopened),sum(release$LOC),sum(release$Total.num.days),sum(release$Num.eff.dev.hours),sum(release$Num.eff.testing.hours),nrow(release[release$Severity=='High',]),nrow(release[release$Severity=='Medium',]),nrow(release[release$Severity=='Low',]),nrow(release[release$Priority=='High',]),nrow(release[release$Priority=='Medium',]),nrow(release[release$Priority=='Low',]))
  x<-cbind("Release_num"=i,x)
  names(x)<-c("Release_num","NumActive","NumDaysActive","NumReopened","Tot_LOC","Tot_Days","Tot_Dev_Hrs","Tot_Test_Hrs","Num_Sev_High","Num_Sev_Med","Num_Sev_Low","Num_Priot_High","Num_Priot_Med","Num_Priot_Low")
  output_dataset<-rbind(output_dataset,x)
}

output_model_TotDays<-lm(Tot_Days ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_DevHrs<-lm(Tot_Dev_Hrs ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_testHrs<-lm(Tot_Test_Hrs ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_high_model<-lm(Num_Sev_High ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_medium_model<-lm(Num_Sev_Med ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_low_model<-lm(Num_Sev_Low ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_priot_high_model<-lm(Num_Priot_High ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_priot_medium_model<-lm(Num_Priot_Med ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_priot_low_model<-lm(Num_Priot_Low ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
summary(output_model_TotDays)
# Shrinked file graph using ggplot
input = readline('Press Enter to view "Total Number of Days" Trend analysis among all the releases')
a<-ggplot(data=output_dataset,aes(x=NumActive,y=Tot_Days),main="Total Num of Days  Vs.  Number of times Active",xlab='Number of times Active',ylab='Total Num of Days') + geom_point(color='darkblue')
b<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Tot_Days),main="Total Num of Days  Vs.  Number of days Active",xlab='Number of days Active',ylab='Total Num of Days')+ geom_point(color='darkblue')
c<-ggplot(data=output_dataset,aes(x=NumReopened,y=Tot_Days),main="Total Num of Days  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Total Num of Days')+ geom_point(color='darkblue')
d<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Tot_Days),main="Total Num of Days  Vs. Total Lines of Code",xlab='Total Lines of Code',ylab='Total Num of Days') + geom_point(color='darkblue')
grid.arrange(a,b,c,d, ncol=2,top = textGrob("Trend analysis for 'Total Number of Days' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Total Dev Hours" Trend analysis among all the releases')
d<-ggplot(data=output_dataset,aes(x=NumActive,y=Tot_Dev_Hrs),main="Eff. Dev Hours  Vs.  Number of times Active",xlab='Number of times Active',ylab='Eff. Dev Hours') + geom_point(color='darkblue')
e<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Tot_Dev_Hrs),main="Eff. Dev Hours  Vs.  Number of days Active",xlab='Number of days Active',ylab='Eff. Dev Hours') + geom_point(color='darkblue')
f<-ggplot(data=output_dataset,aes(x=NumReopened,y=Tot_Dev_Hrs),main="Eff. Dev Hours  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Eff. Dev Hours') + geom_point(color='darkblue')
g<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Tot_Dev_Hrs),main="Eff. Dev Hours  Vs.  Total Lines of Code",xlab='TotalLines of Code',ylab='Eff. Dev Hours') + geom_point(color='darkblue')
grid.arrange(d,e,f,g, ncol=2,top = textGrob("Trend analysis for 'Total Dev Hours' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Total Testing Hours" Trend analysis among all the releases')
h<-ggplot(data=output_dataset,aes(x=NumActive,y=Tot_Test_Hrs),main="Eff. Testing Hours  Vs.  Number of times Active",xlab='Number of times Active',ylab='Eff. Testing Hours') + geom_point(color='darkblue')
i<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Tot_Test_Hrs),main="Eff. Testing Hours  Vs.  Number of days Active",xlab='Number of days Active',ylab='Eff. Testing Hours') + geom_point(color='darkblue')
j<-ggplot(data=output_dataset,aes(x=NumReopened,y=Tot_Test_Hrs),main="Eff. Testing Hours  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Eff. Testing Hours') + geom_point(color='darkblue')
k<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Tot_Test_Hrs),main="Eff. Testing Hours  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Eff. Testing Hours') + geom_point(color='darkblue')
grid.arrange(h,i,j,k, ncol=2,top = textGrob("Trend analysis for 'Total Testing Hours' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Number of High Severity Defects" Trend analysis among all the releases')
l<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Sev_High),main="Number of High severity defects  Vs.  Number of times Active",xlab='Number of times Active',ylab='Number of High Sev defects') + geom_point(color='darkblue')
m<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Sev_High),main="Number of High severity defects  Vs.  Number of days Active",xlab='Number of days Active',ylab='Number of High Sev defects') + geom_point(color='darkblue')
n<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Sev_High),main="Number of High severity defects  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Number of High Sev defects') + geom_point(color='darkblue')
o<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Sev_High),main="Number of High severity defects  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Number of High Sev defects') + geom_point(color='darkblue')
grid.arrange(l,m,n,o, ncol=2,top = textGrob("Trend analysis for 'Number of High Severity Defects' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Number of Medium Severity Defects" Trend analysis among all the releases')
p<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Sev_Med),main="Number of Medium severity defects  Vs.  Number of times Active",xlab='Number of times Active',ylab='Number of Medium Sev defects') + geom_point(color='darkblue')
q<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Sev_Med),main="Number of Medium severity defects  Vs.  Number of days Active",xlab='Number of days Active',ylab='Number of Medium Sev defects') + geom_point(color='darkblue')
r<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Sev_Med),main="Number of Medium severity defects  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Number of Medium Sev defects') + geom_point(color='darkblue')
s<-ggplot(data=output_dataset,aes(x=Tot_LOC,output_dataset,y=Num_Sev_Med),main="Number of Medium severity defects  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Number of Medium Sev defects') + geom_point(color='darkblue')
grid.arrange(p,q,r,s, ncol=2,top = textGrob("Trend analysis for 'Number of Medium Severity Defects' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Number of Low Severity Defects" Trend analysis for all the releases')
t<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Sev_Low),main="Number of Low severity defects  Vs.  Number of times Active",xlab='Number of times Active',ylab='Number of Low Sev defects') + geom_point(color='darkblue')
u<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Sev_Low),main="Number of Low severity defects  Vs.  Number of days Active",xlab='Number of days Active',ylab='Number of Low Sev defects') + geom_point(color='darkblue')
v<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Sev_Low),main="Number of Low severity defects  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Number of Low Sev defects')+ geom_point(color='darkblue')
w<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Sev_Low),main="Number of Low severity defects  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Number of Low Sev defects')+ geom_point(color='darkblue')
grid.arrange(t,u,v,w, ncol=2,top = textGrob("Trend analysis for 'Number of Low Severity Defects' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Number of High Priority Defects" Trend analysis among all the releases')
x<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Priot_High),main="Number of High priority defects  Vs.  Number of times Active",xlab='Number of times Active',ylab='Number of High Prior defects') + geom_point(color='darkblue')
y<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Priot_High),main="Number of High priority defects  Vs.  Number of days Active",xlab='Number of days Active',ylab='Number of High Prior defects') + geom_point(color='darkblue')
z<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Priot_High),main="Number of High priority defects  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Number of High Prior defects') + geom_point(color='darkblue')
aa<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Priot_High),main="Number of High priority defects  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Number of High Prior defects') + geom_point(color='darkblue')
grid.arrange(x,y,z,aa, ncol=2,top = textGrob("Trend analysis for 'Number of High Priority Defects' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Number of Medium Priority Defects" Trend analysis among all the releases')
bb<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Priot_Med),main="Number of Medium priority defects  Vs.  Number of times Active",xlab='Number of times Active',ylab='Number of Medium Prior defects') + geom_point(color='darkblue')
cc<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Priot_Med),main="Number of Medium priority defects  Vs.  Number of days Active",xlab='Number of days Active',ylab='Number of Medium Prior defects') + geom_point(color='darkblue')
dd<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Priot_Med),main="Number of Medium priority defects  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Number of Medium Prior defects') + geom_point(color='darkblue')
ee<-ggplot(data=output_dataset,aes(x=Tot_LOC,output_dataset,y=Num_Priot_Med),main="Number of Medium priority defects  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Number of Medium Prior defects') + geom_point(color='darkblue')
grid.arrange(bb,cc,dd,ee, ncol=2,top = textGrob("Trend analysis for 'Number of Medium Priority Defects' among all the 30 releases",gp=gpar(fontsize=10, font=2)))
input = readline('Press Enter to view "Number of Low Priority Defects" Trend analysis for all the releases')
ff<-ggplot(data=output_dataset,aes(x=NumActive,y=Num_Priot_Low),main="Number of Low priority defects  Vs.  Number of times Active",xlab='Number of times Active',ylab='Number of Low Prior defects') + geom_point(color='darkblue')
gg<-ggplot(data=output_dataset,aes(x=NumDaysActive,y=Num_Priot_Low),main="Number of Low priority defects  Vs.  Number of days Active",xlab='Number of days Active',ylab='Number of Low Prior defects') + geom_point(color='darkblue')
hh<-ggplot(data=output_dataset,aes(x=NumReopened,y=Num_Priot_Low),main="Number of Low priority defects  Vs.  Number of times Reopened",xlab='Number of times Reopened',ylab='Number of Low Prior defects') + geom_point(color='darkblue')
ii<-ggplot(data=output_dataset,aes(x=Tot_LOC,y=Num_Priot_Low),main="Number of Low priority defects  Vs.  Total Lines of Code",xlab='Total Lines of Code',ylab='Number of Low Prior defects') + geom_point(color='darkblue')
grid.arrange(ff,gg,hh,ii, ncol=2,top = textGrob("Trend analysis for 'Number of Low Priority Defects' among all the 30 releases",gp=gpar(fontsize=10, font=2)))

input = readline('***********************Total Number of days Prediction for future release based on input Features************************')
summary(output_model_TotDays)
plot(output_model_TotDays)
mtext("Validation of Prediction Model for Total number days of QA defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Eff Dev Hours Prediction for future release based on input Features*************************')
summary(output_model_DevHrs)
plot(output_model_DevHrs)
mtext("Validation of Prediction Model for Total Eff Dev Hours of QA defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Eff Testing Hours Prediction for future release based on input Features***********************')
summary(output_model_testHrs)
plot(output_model_testHrs)
mtext("Validation of Prediction Model for Total Eff Testing Hours of QA defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of High Severity Defects Prediction for future release based on input Features***********************')
summary(output_model_svr_high_model)
plot(output_model_svr_high_model)
mtext("Validation of Prediction Model for Total Number of High Severity Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Medium Severity Defects Prediction for future release based on input Features***********************')
summary(output_model_svr_medium_model)
plot(output_model_svr_medium_model)
mtext("Validation of Prediction Model for Total Number of Medium Severity Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Low Severity Defects Prediction for future release based on input Features***********************')
summary(output_model_svr_low_model)
plot(output_model_svr_low_model)
mtext("Validation of Prediction Model for Total Number of Low Severity Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of High Priority Defects Prediction for future release based on input Features***********************')
summary(output_model_priot_high_model)
plot(output_model_priot_high_model)
mtext("Validation of Prediction Model for Total Number of High Priority Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Medium Priority Defects Prediction for future release based on input Features***********************')
summary(output_model_priot_medium_model)
plot(output_model_priot_medium_model)
mtext("Validation of Prediction Model for Total Number of Medium Priority Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)
input = readline('***********************Total Number of Low Priority Defects Prediction for future release based on input Features***********************')
summary(output_model_priot_low_model)
plot(output_model_priot_low_model)
mtext("Validation of Prediction Model for Total Number of Low Priority Defects over future releases", side = 3, line = -21.5,col="red", outer=TRUE)

