options( warn = -1 )

temp = list.files(pattern="release.*")
for (i in 1:length(temp))
{
  assign(paste0("release",i), read.csv(temp[i]))
}

par(mfrow=c(2,2))

for(i in 1:30)
{
  release<-get(paste0("release",i))
  input = readline(paste('Press Enter to view "Number of Times Active" Plot for release',i))
  plot(release$numActive,release$Total.num.days,main=paste0("Total Num of Days  Vs.  Number of times Active\n Release",i))
  plot(release$numDaysActive,release$Total.num.days,main=paste0("Total Num of Days  Vs.  Number of days Active\n Release",i))
  plot(release$numReopened,release$Total.num.days,main=paste0("Total Num of Days  Vs.  Number of times Reopened\n Release",i))
  plot(release$LOC,release$Total.num.days,main=paste0("Total Num of Days  Vs. Lines of Code\n Release",i))
  input = readline(paste('Press Enter to view "Dev Hours" Plot for release',i))
  plot(release$numActive,release$Num.eff.dev.hours,main=paste0("Eff. Dev Hours  Vs.  Number of times Active\n Release",i))
  plot(release$numDaysActive,release$Num.eff.dev.hours,main=paste0("Eff. Dev Hours  Vs.  Number of days Active\n Release",i))
  plot(release$numReopened,release$Num.eff.dev.hours,main=paste0("Eff. Dev Hours  Vs.  Number of times Reopened\n Release",i))
  plot(release$LOC,release$Num.eff.dev.hours,main=paste0("Eff. Dev Hours  Vs.  Lines of Code\n Release",i))
  input = readline(paste('Press Enter to view "Testing Hours" Plot for release',i))
  plot(release$numActive,release$Num.eff.testing.hours,main=paste0("Eff. Testing Hours  Vs.  Number of times Active\n Release",i))
  plot(release$numDaysActive,release$Num.eff.testing.hours,main=paste0("Eff. Testing Hours  Vs.  Number of days Active\n Release",i))
  plot(release$numReopened,release$Num.eff.testing.hours,main=paste0("Eff. Testing Hours  Vs.  Number of times Reopened\n Release",i))
  plot(release$LOC,release$Num.eff.testing.hours,main=paste0("Eff. Testing Hours  Vs.  Lines of Code\n Release",i))
}

graphics.off()
#Shrinking the 30 releases
output_dataset<-data.frame(Rel_Num=double(),Tot_Days=double(),Num_Reop=integer(),Num_Active=integer(),Tot_LOC=integer(),Tot_Dev_Hrs=double(),Tot_Test_Hrs=double(),Num_Sev_High=integer(),Num_Sev_Med=integer(),Num_Sev_Low=integer());
for (i in 1:30)
{
  x<-data.frame(sum(get(paste0("release",i))$numReopened),sum(get(paste0("release",i))$numActive),sum(get(paste0("release",i))$numDaysActive),sum(get(paste0("release",i))$Total.num.days),sum(get(paste0("release",i))$LOC),sum(get(paste0("release",i))$Num.eff.dev.hours),sum(get(paste0("release",i))$Num.eff.testing.hours),nrow(get(paste0("release",i))[get(paste0("release",i))$Severity=='High',]),nrow(get(paste0("release",i))[get(paste0("release",i))$Severity=='Medium',]),nrow(get(paste0("release",i))[get(paste0("release",i))$Severity=='Low',]))
  x<-cbind(kl=i,x)
  names(x)<-c("Release_num","NumReopened","NumDaysActive","NumActive","Tot_Days","Tot_LOC","Tot_Dev_Hrs","Tot_Test_Hrs","Num_Sev_High","Num_Sev_Med","Num_Sev_Low")
  output_dataset<-rbind(output_dataset,x)
}

output_model_TotDays<-lm(Tot_Days ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_DevHrs<-lm(Tot_Dev_Hrs ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_testHrs<-lm(Tot_Test_Hrs ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_high_model<-lm(Num_Sev_High ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_medium_model<-lm(Num_Sev_Med ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)
output_model_svr_low_model<-lm(Num_Sev_Low ~ NumActive+NumReopened+NumDaysActive+Tot_LOC,data = output_dataset)

input = readline('Press Enter to view Total Number of days Prediction for future release based on input Features')
summary(output_model_TotDays)
input = readline('Press Enter to view Total Eff Dev Hours Prediction for future release based on input Features')
summary(output_model_DevHrs)
input = readline('Press Enter to view Total Eff Testing Hours Prediction for future release based on input Features')
summary(output_model_testHrs)
input = readline('Press Enter to view Total Number of High Severity Defects Prediction for future release based on input Features')
summary(output_model_svr_high_model)
input = readline('Press Enter to view Total Number of Medium Severity Defects Prediction for future release based on input Features')
summary(output_model_svr_medium_model)
input = readline('Press Enter to view Total Number of Low Severity Defects Prediction for future release based on input Features')
summary(output_model_svr_low_model)


# Shrinked file graph
par(mfrow=c(2,2))
input = readline('Press Enter to view "Total Number of Days" Trend analysis among all the releases')
plot(output_dataset$NumActive,output_dataset$Tot_Days,main="Total Num of Days  Vs.  Number of times Active")
plot(output_dataset$NumDaysActive,output_dataset$Tot_Days,main="Total Num of Days  Vs.  Number of days Active")
plot(output_dataset$NumReopened,output_dataset$Tot_Days,main="Total Num of Days  Vs.  Number of times Reopened")
plot(output_dataset$Tot_LOC,output_dataset$Tot_Days,main="Total Num of Days  Vs. Total Lines of Code")
input = readline('Press Enter to view "Total Dev Hours" Trend analysis among all the releases')
plot(output_dataset$NumActive,output_dataset$Tot_Dev_Hrs,main="Eff. Dev Hours  Vs.  Number of times Active")
plot(output_dataset$NumDaysActive,output_dataset$Tot_Dev_Hrs,main="Eff. Dev Hours  Vs.  Number of days Active")
plot(output_dataset$NumReopened,output_dataset$Tot_Dev_Hrs,main="Eff. Dev Hours  Vs.  Number of times Reopened")
plot(output_dataset$Tot_LOC,output_dataset$Tot_Dev_Hrs,main="Eff. Dev Hours  Vs.  Total Lines of Code")
input = readline('Press Enter to view "Total Testing Hours" Trend analysis among all the releases')
plot(output_dataset$NumActive,output_dataset$Tot_Test_Hrs,main="Eff. Testing Hours  Vs.  Number of times Active")
plot(output_dataset$NumDaysActive,output_dataset$Tot_Test_Hrs,main="Eff. Testing Hours  Vs.  Number of days Active")
plot(output_dataset$NumReopened,output_dataset$Tot_Test_Hrs,main="Eff. Testing Hours  Vs.  Number of times Reopened")
plot(output_dataset$Tot_LOC,output_dataset$Tot_Test_Hrs,main="Eff. Testing Hours  Vs.  Total Lines of Code")
input = readline('Press Enter to view "Number of High Severity Defects" Trend analysis among all the releases')
plot(output_dataset$NumActive,output_dataset$Num_Sev_High,main="Number of High severity defects  Vs.  Number of times Active")
plot(output_dataset$NumDaysActive,output_dataset$Num_Sev_High,main="Number of High severity defects  Vs.  Number of datys Active")
plot(output_dataset$NumReopened,output_dataset$Num_Sev_High,main="Number of High severity defects  Vs.  Number of times Reopened")
plot(output_dataset$Tot_LOC,output_dataset$Num_Sev_High,main="Number of High severity defects  Vs.  Total Lines of Code")
input = readline('Press Enter to view "Number of Medium Severity Defects" Trend analysis among all the releases')
plot(output_dataset$NumActive,output_dataset$Num_Sev_Med,main="Number of Medium severity defects  Vs.  Number of times Active")
plot(output_dataset$NumDaysActive,output_dataset$Num_Sev_Med,main="Number of Medium severity defects  Vs.  Number of datys Active")
plot(output_dataset$NumReopened,output_dataset$Num_Sev_Med,main="Number of Medium severity defects  Vs.  Number of times Reopened")
plot(output_dataset$Tot_LOC,output_dataset$Num_Sev_Med,main="Number of Medium severity defects  Vs.  Total Lines of Code")
input = readline('Press Enter to view "Number of Low Severity Defects" Trend analysis for all the releases')
plot(output_dataset$NumActive,output_dataset$Num_Sev_Low,main="Number of Low severity defects  Vs.  Number of times Active")
plot(output_dataset$NumDaysActive,output_dataset$Num_Sev_Low,main="Number of Low severity defects  Vs.  Number of datys Active")
plot(output_dataset$NumReopened,output_dataset$Num_Sev_Low,main="Number of Low severity defects  Vs.  Number of times Reopened")
plot(output_dataset$Tot_LOC,output_dataset$Num_Sev_Low,main="Number of Low severity defects  Vs.  Total Lines of Code")
input = readline('')
